on:
    push:
        branches:
            - master
            
jobs:
    update-projectstoc:
        runs-on: ubuntu-20.04
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: set up python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: '3.8'
            - name: install
              run: |
                  python -m pip install --upgrade pip
                  pip install pytz
                  
